# Source: fluxCDConfigGenerator/templates/gitrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-demo
  namespace: flux-demo
spec:
  interval: 1m
  url: <git_repo_url>
  ref:
    branch: main
  secretRef:
    name: flux-pat
---
# Source: fluxCDConfigGenerator/templates/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-demo
  namespace: flux-demo
spec:
  #  suspend: true
  releaseName: nginx-demo
  timeout: 5m
  interval: 1m
  chart:
    spec:
      chart: hello-world
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: nginx-demo
  # values:
  #   replicaCount: 2
  # postRenderers:
  #   - kustomize:
  #       patchesStrategicMerge:
  #         - kind: Deployment
  #           apiVersion: apps/v1
  #           metadata:
  #             name: nginx-demo-hello-world
  #           spec:
  #             template:
  #               metadata:
  #                 labels:
  #                   test: test

